#!/usr/bin/env python3
"""Build a single-file version of the internship board.

The standalone file inlines the stylesheet, current job snapshot, and application
JavaScript. Relative links to the CSV, email library, and deployment guide remain
available when the file sits at the project root (or in the generated public site).
"""
from __future__ import annotations

import argparse
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[1]

_STYLESHEET_TAG = '  <link rel="stylesheet" href="styles.css">'
_SCRIPT_TAGS = '  <script src="data/jobs.js"></script>\n  <script src="app.js"></script>'


def _safe_inline_script(source: str) -> str:
    """Prevent an embedded ``</script>`` sequence from ending the tag early."""
    return source.replace("</script", "<\\/script")


def build(root: Path = DEFAULT_ROOT, output: Path | None = None) -> Path:
    root = root.resolve()
    output = (output or (root / "standalone.html")).resolve()

    html = (root / "index.html").read_text(encoding="utf-8")
    css = (root / "styles.css").read_text(encoding="utf-8")
    jobs_js = _safe_inline_script((root / "data" / "jobs.js").read_text(encoding="utf-8"))
    app_js = _safe_inline_script((root / "app.js").read_text(encoding="utf-8"))

    if _STYLESHEET_TAG not in html:
        raise ValueError("Could not find the expected stylesheet tag in index.html")
    if _SCRIPT_TAGS not in html:
        raise ValueError("Could not find the expected application script tags in index.html")

    html = html.replace(
        _STYLESHEET_TAG,
        "  <!-- Generated by scripts/build_standalone.py -->\n  <style>\n"
        + css.rstrip()
        + "\n  </style>",
        1,
    )
    html = html.replace(
        _SCRIPT_TAGS,
        "  <script>\n"
        + jobs_js.rstrip()
        + "\n  </script>\n  <script>\n"
        + app_js.rstrip()
        + "\n  </script>",
        1,
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(html, encoding="utf-8")
    return output


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=DEFAULT_ROOT,
        help="Directory containing index.html, styles.css, app.js, and data/jobs.js.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path. Defaults to <root>/standalone.html.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    output = build(args.root, args.output)
    print(f"Built standalone board at {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
